# Generated by Django 5.0.3 on 2024-03-28 19:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('weather', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=254)),
                ('fcast_date', models.DateField()),
                ('avg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('hours_count', models.PositiveSmallIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'unique_together': {('owner', 'city_name', 'fcast_date')},
            },
        ),
    ]
